spring:
  application:
    name: leftover-blind-box-backend

  # 环境
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    # 控制台打印SQL
    map-underscore-to-camel-case: true                      # 开启驼峰映射
  global-config:
    db-config:
      id-type: auto