spring:
  # 数据库配置 - MySQL
  datasource:
    url: jdbc:mysql://switchyard.proxy.rlwy.net:45560/railway?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: kQTxThIsfCbaxQtADFRuGDZnfYisZYGH
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.security: DEBUG

# ---------- JWT 配置 ----------
jwt:
  secret: k3b8Xq1v2Zm9Yp6Wn5Lr8As3Dx7Cv1Bn9Mq4Xs8Vj2Kp5Lw9Zt6Eq4Am8Nq1Vp5Lw9Zt6Eq4Am8Nq1Vp5Lw9Zt6Eq4A==
  expire-time: 3600000

rsa:
  public-key-path: .keys/public-key.pem
  private-key-path: .keys/private-key.pem