spring:
  # 数据库配置 - MySQL
  datasource:
    url: jdbc:mysql://nozomi.proxy.rlwy.net:26543/railway?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: RzyhRxPmpHekutjdLQtGDDqeDtTEJwkQ
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: shinkansen.proxy.rlwy.net
      port: 37325
      password: kSBzZtCxzRzBKEsejmNMmsQREiWvLthk
      connect-timeout: 5s

      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: 200ms
          min-idle: 0


logging:
  level:
    org.springframework.security: DEBUG

# ---------- JWT 配置 ----------
jwt:
  secret: k3b8Xq1v2Zm9Yp6Wn5Lr8As3Dx7Cv1Bn9Mq4Xs8Vj2Kp5Lw9Zt6Eq4Am8Nq1Vp5Lw9Zt6Eq4Am8Nq1Vp5Lw9Zt6Eq4A==
  expire-Minutes: 120  #小时
  renew-threshold-minutes: 30

rsa:
  boot: false
  public-key-path: .keys/public-key.pem
  private-key-path: .keys/private-key.pem