spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_HOST:6379}
      password: ${SPRING_REDIS_PASSWORD}
      connect-timeout: 5s

      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: 200ms
          min-idle: 0
