server:
  port: 10016

spring:
  # ========== 禁用 JPA 自动配置 ==========
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

  # 数据库配置 - MySQL
  datasource:
    url: jdbc:mysql://nozomi.proxy.rlwy.net:26543/railway?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: RzyhRxPmpHekutjdLQtGDDqeDtTEJwkQ
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: shinkansen.proxy.rlwy.net
      port: 37325
      password: kSBzZtCxzRzBKEsejmNMmsQREiWvLthk
      connect-timeout: 5s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: 200ms
          min-idle: 0

  mail:
    host: smtp.gmail.com
    port: 587
    username: magicbag.noreply@gmail.com
    password: pwnu enib nibx mbny
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  application:
    name: leftover-blind-box-backend

# ---------- JWT 配置 ----------
common:
  url: ${APP_URL:http://localhost:10016}
  jwt:
    secret: k3b8Xq1v2Zm9Yp6Wn5Lr8As3Dx7Cv1Bn9Mq4Xs8Vj2Kp5Lw9Zt6Eq4Am8Nq1Vp5Lw9Zt6Eq4Am8Nq1Vp5Lw9Zt6Eq4A==
    expire-minutes: 120
    renew-threshold-minutes: 30
  rsa:
    boot: false
    public-key-path: .keys/public-key.pem
    private-key-path: .keys/private-key.pem

# ---------- URL 配置 ----------
app:
  pay-url: http://localhost:10016

# ---------- Stripe 配置 ----------
stripe:
  api:
    key: sk_test_51QkKIAFx9r3W1cEdHhvIXcgV4oTkl7KlnA7vLuFDttGigZxNaTiiw4VR7nWFCQxssdTnzjgX2376tBdYNx9UniYJ00GwesjEGB

# ---------- MyBatis-Plus 配置 ----------
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

# ---------- SpringDoc 配置 ----------
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  group-configs:
    - group: 'public-api'
      paths-to-match: '/api/**'
      packages-to-scan: nus.iss.se.magicbag.controller