server:
  port: 10016

spring:
  # 数据库配置 - MySQL
  datasource:
    url: jdbc:mysql://nozomi.proxy.rlwy.net:26543/railway?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: RzyhRxPmpHekutjdLQtGDDqeDtTEJwkQ
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: shinkansen.proxy.rlwy.net
      port: 37325
      password: kSBzZtCxzRzBKEsejmNMmsQREiWvLthk
      connect-timeout: 5s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: 200ms
          min-idle: 0

  mail:
    host: smtp.gmail.com
    port: 587
    username: magicbag.noreply@gmail.com
    password: pwnu enib nibx mbny
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# ---------- JWT 配置 ----------
common:
  jwt:
    secret: k3b8Xq1v2Zm9Yp6Wn5Lr8As3Dx7Cv1Bn9Mq4Xs8Vj2Kp5Lw9Zt6Eq4Am8Nq1Vp5Lw9Zt6Eq4Am8Nq1Vp5Lw9Zt6Eq4A==
    expire-minutes: 120
    renew-threshold-minutes: 30
  rsa:
    boot: false
    public-key-path: .keys/public-key.pem
    private-key-path: .keys/private-key.pem

# ---------- URL 配置 ----------
app:
  pay-url: http://localhost:10016

# ---------- Stripe 配置 ----------
stripe:
  api:
    key: sk_test_51QkKIAFx9r3W1cEdHhvIXcgV4oTkl7KlnA7vLuFDttGigZxNaTiiw4VR7nWFCQxssdTnzjgX2376tBdYNx9UniYJ00GwesjEGB
