spring:
  application:
    name: leftover-blind-box-backend

  # 环境
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    # 控制台打印SQL
    map-underscore-to-camel-case: true                      # 开启驼峰映射
  global-config:
    db-config:
      id-type: auto

# springdoc 配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  # 分组配置（可选）
  group-configs:
    - group: 'public-api'
      paths-to-match: '/api/**'
      packages-to-scan: nus.iss.se.magicBag.controller